apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::482854218041:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-rySBiGU1kBXz
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::482854218041:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-26T18:25:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5002"
  uid: de53a721-b256-48cd-9f66-99d075a0c75c
